version: '3.8'
services:
  postgres: 
     container_name: threads-db
     image: postgres
     environment:
       POSTGRES_USER: postgres
       POSTGRES_DB: threads
       POSTGRES_PASSWORD: threads
     ports:
       - "5432:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: